### PR TITLE
Song syntax and ordering fixes

### PR DESCRIPTION
**Pull request by DonnieWest**

### CODE REVIEW

**Comment by DonnieWest** [comment]
Unfortunately, I already deployed this. All these changes are live currently and I'm working on something to build our site and deploy it as is

**Comment by trepidity** [comment]
UGH!!! we will have to add "0" to a lot of files :)

**Comment by DonnieWest** [comment]
Ugh. Forgot my changes to my repo were still being reflected in this pull request. About half of those weren't for you and were going to be squashed >.>

**Comment by trepidity** [comment]
If you want, we can handle our own merging? We can just comment on each
others PR if we want input. I would like to approve each others, that way
when I miss something you will save my butt! :) but i'm cool if we merge
our own PR's after that.

**Comment by DonnieWest** [comment]
Just so you know, totally my fault. I should've known better than to do all that. Each set of changes should've been in their own branch and not the crazy I pulled :-P 

I'm fine either way though on merging or not merging our own PRs. Whatever you feel most comfortable with

**Comment by trepidity** [comment]
LOL all good.

**Pull request merged**
